name: fractions
description: Simple math fractions library. Library create simple fraction and define basic math operations.
version: pre-v0.1 release
homepage: https://github.com/adamjak/dart_fractions

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_numerics: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
